#site_name: IR â€“ Pell Accepts Pipeline
site_name: ir-pell-accepts
site_description: Institutional Research Python pipeline documentation
site_author: Office of Decision Support

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy

nav:
  - Overview: index.md
  - Setup:
      - Installation: setup.md
      - Environment: environment.md
  - Pipeline:
      - Overview: pipeline.md
      - Configs: configs.md
  - Notebooks: notebooks.md
  - Code Reference: SUMMARY.md   # <-- add this

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
            - ir-pipelines/ir-pell-accepts/src
          options:
            show_source: false
            show_signature_annotations: true
            docstring_section_style: table
#  - mkdocstrings:
#      handlers:
#        python:
#          options:
#            show_source: false
#            show_signature_annotations: true
#            docstring_section_style: table
