[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ir_team_exercise"
version = "0.1.0"
description = "New package"

[tool.setuptools.packages.find]
where = ["src"]
