# config/config.yaml
# note the use of forward slashes for file paths
# file types need to stay the same: do not change from xlxs to csv and vice-versa

user:
  name: "Sean"
  box_root: "C:/Users/sruddy1/Box"

box_repo:
  pell_dir: "Office of Decision Support Analyst Projects/ATI Kessler/Fall 2025 Pell Reporting"
  pell_file: "Pell Recipients by Academic Term or Year 25-11-26.xlsx"
  retention_dir: "Inst Res Collab/Tableau Server Data Sources/Retention"
  retention_file: "Undergraduate Retention and Graduation.csv"
  enrollment_dir: "Inst Res Collab/Tableau Server Data Sources/Census Date Enrollment"
  enrollment_file: "Census Date Enrollment (Decision Support Curated).csv"
  results_dir: "Inst Res Collab/Team Retreat Pipeline Results"
  results_file: "University of Dayton 2025 ATI Prelim.xlsx"

params:
  term: "202580"
  id_column: "ID"
  ipeds_acad_year: "2017-2018"

